server:
    port: 8080
spring:
    profiles:
        active:
            - prod

---
spring:
    config:
        activate:
            on-profile:
                - prod
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: jdbc:h2:mem:temp
        username: sa
        password: 1234
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.H2Dialect
    jwt:
        secret: dreamideasoft
        expirationMs: 60000 # 1min
        refreshExpirationMs: 120000 # 2min
logging:
    level:
        "[org.hibernate]": error
        # "[org.springframework]": debug
server:
    error:
        include-message: always
